### ISSUE TITLE
question

### ISSUE THREAD

**Issue by lty646** [JorgeGIlG/MTF_Estimator#13]
Hi~I am a beginner of MTF.
Is your method called FidMTF？Full name？
And is the calculated MTF more accurate？

**Comment by JorgeGIlG** [comment]
Hi,
Yes, the method's name is FidMTF. _Fid_ stands for _fidelity_.
I developed it to be used when you don't have high-quality targets at hand (as it usually happens with satellite imagery) and ISO12233-based methods fail. I encourage you to test the method yourself. To do so you can, for example, create your own synthetic MTF targets. There is a target creation example in the code.

**Comment by lty646** [comment]
I am a student of researching RS image processing and mapping.
I've been doing resampling based on observation model recently, and need Gaofen-2's MTF at the nyquist frequency, there is no official information was provided, so I want to calculate it. Then found your method~
My point is not MTF, so I won't spend time studying it at present. If the calculated results are consistent with the official range, I will use your method.
Thanks for sharing your code.

**Comment by JorgeGIlG** [comment]
Great. 
Please just remember that, for a given sensor, it is customary to provide MTF values for images after radiometric correction and **before** any resampling. As you may know, once resampled it is difficult to decouple the part attributable to the sensor to the one corresponding to the resampling itself.

**Comment by lty646** [comment]
Why the MTF at the nyquist frequency is pretty low?
![1641900064(1)](https://user-images.githubusercontent.com/70827687/148933689-fe2e45c4-51cf-4900-9f5d-f0d580207e7a.jpg)
The resolution of Gaofen-2 multispectral image is 4m, and the official range is more than 0.24...
![1641900381(1)](https://user-images.githubusercontent.com/70827687/148934455-cfe0ccef-1c37-4247-8d2b-ff932aa720da.jpg)

**Comment by JorgeGIlG** [comment]
According to [eoporta](https://directory.eoportal.org/web/eoportal/satellite-missions/g/gaofen-2):
_The statically measured MTF in the lab is 0.12 for PAN, and 0.2 for MS data. **in lab condition**. On orbit, the dynamic MTF is 0.1 at Nyquist frequency._

The figures you have are for laboratory conditions. The MTF@Nyquist is lower on orbit with the spacecraft in motion and atmosphere. It will be definitively much lower if your image is orthorectified, because it has been **resampled**. Is it the case?

Estimating the MTF@Nyquist is problematic because it is where the information vanishes, that's why MTF30 & MTF50 figures are also provided. I recommend you to read this excellent [document](https://www.imatest.com/docs/sharpness/) from Imatest. If you are not satisfied with the explanation you can also try their software and compare the results. I think there is a trial version.

**Comment by lty646** [comment]
Ah oh~right, the test data is preprocessing in ENVI.
I find your method is extremely demanding on the selection of targets. I tested many targets, and just a few of them show final results...
I used Sentinel-2 data to do experiment, there was no result...Does it not work for data with a resolution of more than 10m?

**Comment by JorgeGIlG** [comment]
Yes indeed. It avoids yielding wrong results by demanding good edges. 

The method works if the edges are good enough. It would work for 10m or more if you could find a good edge.

For reference about sites and methods to measure the MTF on Sentinel-2 see this [document ](https://sentinel.esa.int/documents/247904/2047089/Sentinel-2_Cal-Val_Phase-E2), section 3.3.2.9.4.1 and table 3-1.

**Comment by JorgeGIlG** [comment]
BTW. For Sentinel-2 you need a product that hasn't been resampled i.e [L1B](https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-2-msi/level-1b-processing)

**Comment by lty646** [comment]
Okay~I will pay attention to the information you mentioned，I really appreciate it.
If I have any questions，I‘ll contact with you in time.
