### ISSUE TITLE
Use for CEOS purposes?

### ISSUE THREAD

**Issue by PC-TPZ** [JorgeGIlG/MTF_Estimator#14]
Hello!

We've been using the MTF_Estimator for quick open-source MTF evaluations of CEOS reference images (see https://opg.optica.org/oe/fulltext.cfm?uri=oe-26-26-33625&id=402992  and https://calvalportal.ceos.org/).
We adapted mtf_estimator.py to give us a data readout of MTF at Normalised frequency intervals of 0.02 to conform with CEOS requirements.

The results are looking to us very good, stable and encouraging! We wonder if the plug-in conforms to any ISO standards?

Please let us know if you don't wish to provide these outputs to CEOS. At all stages we are referencing these pages.
Many thanks,
Pauline Cocevar
Telespazio UK

**Comment by JorgeGIlG** [comment]
Hi Pauline,

Thank you for your message. I it is satisfying to know that the algorithm is being used.
I wrote it to overcome some limitations of the ISO 12233 when working with remotely-sensed optical data. For this reason it doesn't conform to any standard. 
As you know the software is open source, you are free to use, modify and redistribute it according to the license.
I'm happy to know that you are providing the results to CEOS. Your work is yours and of course you don't need my approval, but letting me know is very kind of you.

I would be grateful if you could just keep some form of attribution, maybe pointing to the source code on GitHub (https://github.com/JorgeGIlG/MTF_Estimator).

Keep me posted, please!

Regards,
Jorge.


Dec 13, 2022, 15:55 by ***@***.***:

**Comment by PC-TPZ** [comment]
Hi Jorge,

Thank you for your reply and being happy with our use of the Estimator. Of interest, what did you see as the limitations of ISO 12233 for remotely-sensed optical data?

We are referencing the repository page at every stage, and will let you know when we get to the end of our engagement with CEOS.

Many thanks!
Best wishes,
Pauline

**Comment by JorgeGIlG** [comment]
Hi Pauline,

As far as I can remember the algorithm described by the ISO 12233 was very sensitive to imperfections on the test data. It is not a problem when working in the laboratory conditions the document authors had in mind, but it is not the scenario for remotely sensed data, as you know. Ground targets such as Stennis, Baotou, etc. can be dirty. For lower resolutions it is even worse since there are not MTF targets large enough and it necessary to rely on other artificial structures (e.g. parking lots). For this reason I decided to create a more robust one, tolerant to some extent to such imperfections.

Cheers.
Jorge.

**Comment by JorgeGIlG** [comment]
Also, I am not sure if the ISO 12233 covers pushbroom sensros....

**Comment by PC-TPZ** [comment]
Hi Jorge,
Thank you for the extra information, which is good to know.
Thanks again for the help, and I hope you have an enjoyable Christmas!
-Pauline
